---
- hosts: local
  tasks:
  - debug:
      msg: "{{ greetings }}"
      verbosity: 0

  - name: Create a directory if it does not exist
    file:
      path: ../repo/
      state: directory
      mode: '0755'
      
  - name: Touch the same file, but add/remove some permissions
    file:
      path: ../repo/whut.txt
      state: touch
      mode: u+rw,g-wx,o-rwx
    
  - shell: "ls -la ../ >> ../repo/whut.txt"
  
  - shell: "cat ../repo/whut.txt"
    register: myVar
