---
- hosts: local
  tasks:
  - debug:
      msg: "{{ greetings }}"
      verbosity: 0

  - name: "Create a directory if it does not exist {{ greetings }}"
    file:
      path: ../repo/
      state: directory
      mode: '0755'
      
  - stat:
      path: ../repo/new.json
    register: projectFile
  
  - debug:
      msg: "{{ projectFile }}"
    
  - name: Make sure the json file exists
    file:
      path: ../repo/new.json
      state: touch
      mode: '0755'    
    when: projectFile.stat.exists is false
  
  - shell: "echo '{}' > ../repo/new.json"
    when: projectFile.stat.exists is false
        
  - name: Test Project exists
    json_patch:
      src: "../repo/new.json"
      operations:
        - op: add
          path: "/storelink"
          value: {
            dev: { current: "" },
            prod: { current: "" },
            versions: []
          }
    register: myVar
    
  - debug:
      msg: "{{ myVar }}"
      
  - name: Ensure The storelink exists in the list
    json_patch:
      src: "../repo/new.json"
      operations:
        - op: test
          path: "/*"
          value: "storelink"
    register: linkExists
    
  - debug:
      msg: "{{ linkExists }}"
      
  #- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  #  archive:
  #    path: ../
  #    dest: ../_attachments/files.tgz
