---
- hosts: local
  tasks:
  - debug:
      msg: "{{ greetings }}"
      verbosity: 0
  - shell: "touch ./file.txt"
  - shell: "echo 'omg' > ./file.txt"
  - file:
    path: _attachments/whut.txt
    state: touch
  - shell: "ls -la > _attachments/whut.txt" 
  
