---
- hosts: local
  tasks:
  - debug:
      msg: "{{ greetings }}"
      verbosity: 0

  - name: Create a directory if it does not exist
    file:
      path: ../repo/
      state: directory
      mode: '0755'
      
  - name: Touch the same file, but add/remove some permissions
    file:
      path: ../repo/whut.json
      state: touch
      mode: u+rw,g-wx,o-rwx
    
  - shell: "echo '{}' > ../repo/whut.json"
    
  - name: Add or replace 'baz' member
    json_patch:
      src: "../_attachments/test.json"
      operations:
        - op: add
          path: "/baz"
          value: "quz"
    register: myVar
    
  #- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  #  archive:
  #    path: ../
  #    dest: ../_attachments/files.tgz
