---
- hosts: local
  tasks:
  - debug:
      msg: "{{ greetings }}"
      verbosity: 0

  - name: "Create a directory if it does not exist {{ greetings }}"
    file:
      path: ../repo/
      state: directory
      mode: '0755'
      
  - stat:
      path: ../repo/new.json
    register: projectFile
  
  - debug:
      msg: "{{ p }}"
      
  - shell: "echo '{}' > ../repo/new.json"
    when: projectFile.stat.exists is false
  
  - name: Make sure the json file exists
    file:
      path: ../repo/new.json
      state: touch
      mode: '0755'
        
  - name: Add or replace 'baz' member
    json_patch:
      src: "../repo/new.json"
      operations:
        - op: add
          path: "/baz/-"
          value: "quz"
    register: myVar
    
  #- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  #  archive:
  #    path: ../
  #    dest: ../_attachments/files.tgz
